title: "Ariana Oyola"
description: "Portafolio personal de Ariana Oyola"
theme: minima

plugins:
  - jekyll-data

markdown: kramdown

# Configuración de URL base (útil si está en GitHub Pages)
baseurl: "" 
url: "https://tuusuario.github.io"
